- name: Testing
  hosts: localhost
  become: no
  gather_facts: false
  
  tasks:
  - name: Testing
    debug:
      msg: "Testing 123"
  
- hosts: localhost
  connection: local
  become: no
  gather_facts: true
  roles:
   - osp-servers
